### PR TITLE
Implement tinymce 3.5.11 (Includes IE11 support)

### PR DESCRIPTION
**Pull request by maethu**
Hi all!

I've created a new branch in the [collective/tinymce repo, called 3.5.11-TEST](https://github.com/collective/tinymce/tree/3.5.11-plone-TEST)

This tinymce branch contains all fixes until [tinymce 3.5.11](https://github.com/collective/tinymce/blob/3.5.11-plone-TEST/changelog.txt)

I applied all plone patches, by following the instructions on http://productstinymce.readthedocs.org/en/latest/develop.html#getting-a-new-upstream-version

Afterwards I faced some small Issues:
- https://github.com/collective/tinymce/commit/6ed6718b263c6429b9bcc7f338fd7e18f09c52ac (Fix a undefined var.)
- https://github.com/collective/tinymce/commit/e810d934cec4018b0cedb4e39a4fd771a865b00d (Make the cell/column/table popup work with the customized plone template.)

This PR is built on top of the 3.5.11-TEST tinymce branch and needs some **testing** from other people, who like to use Plone 4.3.x with IE 11 support :smile: 

Changes I recognised so far (Don't know if those are merge accidents, features, or bugs):
- It works now with IE 11
- Chrome/FireFox also still works. 
- ~~jquery-integration.js needs to be enabled.~~
- Setting a cell/table/column with/height now also works (if safe_html transform is configured accordingly).
- The table column popup ist not styled properly.
screen shot 2015-05-05 at 17 18 14

**Problems while creating this PR:**

The `upgrade_tinymce.sh` is outdated - I guess i doesn't work since 2-3 years.
This means the website with the language source `services.moxiecode.com` is no longer available. 
The scripts still runs if you download the language pack manually. 
Upgrading tinymce with the script was fine, but all plone relevant addons were broken, so I chose to use the files from https://github.com/collective/tinymce/tree/3.5.8-plone. 
I also was not able to build the new translations(*.po) files. As far as I can see french and italian languages were improved. 

As much people as possible should test this PR, so we can :ship: a new Release of Products.TinyMCE for Plone 4.3.x with IE 11 support. IMHO is currently stable, but it's really hard to say, since this thingy is very complex.

Tasks:
- [x] Should work without jquery-integration.js

### CODE REVIEW

**Comment by jone** [comment]
If tested it a little, it seems to work quite well!

**Comment by steve84** [comment]
We've also tested the branch and it looks good at first sight.

**Comment by maethu** [comment]
@steve84 thanks for testing!

**Comment by mbaechtold** [comment]
I've manually tested the basics (formatting, links, tables, etc.) in IE 11 on Win 8.1 and I didn't encounter any bug.

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/156/

**Comment by maethu** [comment]
@jensens This PR points to the Plone 4.3 support branch -> plone:1.3.x , not Plone 5, so the label `pr p5.0`is wrong. Since you're managing the labels, can you change it? or should I?

**Comment by jensens** [comment]
Please do it! I just set the labels initially - that does not mean that I want to do it all my life :)

**Comment by jensens** [comment]
btw: so the test was also at the wrong place
here we go http://jenkins.plone.org/view/All/job/pull-request-4.3/19/

**Comment by do3cc** [comment]
I've rebased the PR, but it is on its own branch now, ie11_for_1.3.x
I haven'd tried it yet, because my client forgot to add ie11 to my client provided work machine :-)
Can this PR somehow point to my branch or do I need a new PR?

**Comment by jensens** [comment]
hmm, not sure, but afaik you need a new PR

**Comment by do3cc** [comment]
I close this PR because I continue the same PR here: https://github.com/plone/Products.TinyMCE/pull/105

**Pull request closed without merging**
