### PR TITLE
 Fix TinyMCE Firefox  Range.prototype error

### PR DESCRIPTION
**Pull request by ichim-david**
The change is really simple but it's hard to spot in this changeset because tiny_mce.js and tiny_mce_jquery.js are minified.

basically this if statement:
if (!Range.prototype.getClientRects) {
is changed to:
if (!Range.prototype) {

since in Firefox Range.prototype is undefined.
Without this fix there are two potential failures:
1. Clicking on the style list will not bring up the style dropdown
2. Upon saving the object, after editing again the tinymce textarea is empty even though the html is present if you click the html button.

### CODE REVIEW

**Comment by jensens** [comment]
Is this one still valid?

**Comment by ichim-david** [comment]
@jensens  Yes it is, I've check the tiny_mce.js file and the check is still present.

**Comment by jensens** [comment]
Can you please rebase your PR with master, so I can merge it?

**Comment by ichim-david** [comment]
I've updated my fork although I don't know if you will be able to see the change that I've done properly within the diff of github.

**Comment by jensens** [comment]
still needs rebase, change does not show up.

**Comment by do3cc** [comment]
@ichim-david your change showed up but it is still outdated. I guess this might be, because it was a long time ago again. @jensens sees to many messages every day, maybe this is when he didn't respond earler. I don't see that many messages per day and should be able to merge quicker. Sorry for the delay :-)

**Comment by ichim-david** [comment]
I didn't get a good merge as such I've made a fresh repo fork and added the change there.
Closing this pull request,  the same conversation can be resumed here:
https://github.com/plone/Products.TinyMCE/pull/113

@jensens I've redone the pull request, I will also make a pull request f for the 1.3.x branch

**Pull request closed without merging**
