### PR TITLE
Show anchor dropdown for internal links again if it was empty once

### PR DESCRIPTION
**Pull request by msom**
The dropdown is not visible if it once has been empty.

### CODE REVIEW

**Comment by jensens** [comment]
May you add a line to the changelog please?

**Comment by msom** [comment]
Changelog changed with https://github.com/plone/Products.TinyMCE/commit/cd934e4ff4c620cae2bca350d8eb5309053768b0

**Comment by jensens** [comment]
thanks, after rebase we can merge

**Comment by msom** [comment]
Done :)

**Pull request merged**
