### PR TITLE
Ie11 for 1.3.x

### PR DESCRIPTION
**Pull request by do3cc**
This is the continuation of https://github.com/plone/Products.TinyMCE/pull/94
Since I cant work on the branch that is used there

### CODE REVIEW

**Comment by do3cc** [comment]
maethu commented on 5 May

Hi all!

I've created a new branch in the [collective/tinymce repo, called 3.5.11-TEST](https://github.com/collective/tinymce/tree/3.5.11-plone-TEST)

This tinymce branch contains all fixes until [tinymce 3.5.11](https://github.com/collective/tinymce/blob/3.5.11-plone-TEST/changelog.txt)

I applied all plone patches, by following the instructions on http://productstinymce.readthedocs.org/en/latest/develop.html#getting-a-new-upstream-version

Afterwards I faced some small Issues:
- https://github.com/collective/tinymce/commit/6ed6718b263c6429b9bcc7f338fd7e18f09c52ac (Fix a undefined var.)
- https://github.com/collective/tinymce/commit/e810d934cec4018b0cedb4e39a4fd771a865b00d (Make the cell/column/table popup work with the customized plone template.)


This PR is built on top of the 3.5.11-TEST tinymce branch and needs some **testing** from other people, who like to use Plone 4.3.x with IE 11 support :smile: 


Changes I recognised so far (Don't know if those are merge accidents, features, or bugs):
- It works now with IE 11
- Chrome/FireFox also still works. 
- ~~jquery-integration.js needs to be enabled.~~
- Setting a cell/table/column with/height now also works (if safe_html transform is configured accordingly).
- The table column popup ist not styled properly.
screen shot 2015-05-05 at 17 18 14


**Problems while creating this PR:**

The `upgrade_tinymce.sh` is outdated - I guess i doesn't work since 2-3 years.
This means the website with the language source `services.moxiecode.com` is no longer available. 
The scripts still runs if you download the language pack manually. 
Upgrading tinymce with the script was fine, but all plone relevant addons were broken, so I chose to use the files from https://github.com/collective/tinymce/tree/3.5.8-plone. 
I also was not able to build the new translations(*.po) files. As far as I can see french and italian languages were improved. 


As much people as possible should test this PR, so we can :ship: a new Release of Products.TinyMCE for Plone 4.3.x with IE 11 support. IMHO is currently stable, but it's really hard to say, since this thingy is very complex.

Tasks:
- [x] Should work without jquery-integration.js

**Comment by do3cc** [comment]
Jensens commented:

btw: so the test was also at the wrong place
here we go http://jenkins.plone.org/view/All/job/pull-request-4.3/19/
- [ ] ok
- [x] fails

**Comment by do3cc** [comment]
Several people commented that it works fine for them.
Works fine for us too, but I'll have a look at the open issues mentioned above.

**Comment by do3cc** [comment]
I can reproduce the issue mentioned in the screenshot above. Unfortunately the new html has been replaced completely for this file and is missing the right css classes. I am going to add them next week

**Comment by do3cc** [comment]
I cleanup the styling.
I'd love to see somebody else look at it too. @maethu ?

**Comment by do3cc** [comment]
Lets see what jenkins things

**Comment by maethu** [comment]
Seems like the TinyMCE related tests are passing..
Thank you @do3cc to catching up!

imho it looks fine now

screen shot 2015-06-24 at 08 14 03
screen shot 2015-06-24 at 08 13 46
screen shot 2015-06-24 at 08 13 35

**Comment by maethu** [comment]
I just got one issues:
- I'm not able to run this branch with Plone 4.3.6

``` 
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/Users/maethu/pkgs/Products.TinyMCE/parts/instance/etc/site.zcml", line 12.2-12.39
    ZopeXMLConfigurationError: File "/Users/maethu/.buildout/eggs-cache/Products.CMFPlone-4.3.6-py2.7.egg/Products/CMFPlone/meta.zcml", line 42.4-46.10
    ImportError: No module named CMFPlacefulWorkflow
```
No Issues with Plone 4.3.2, 4.3.3 and 4.3.4 (skipped 4.3.5).

**Comment by do3cc** [comment]
maethu I fixed it locally by using a source checkout from plone.app.upgrade. the version used in 4.3.6 is broken. There are probably a lot of broken travis jobs because of this right now.

**Comment by maethu** [comment]
@do3cc wohoooo :sparkles:  Thanks!!

**Pull request merged**
