### PR TITLE
tinymce-jsonconfiguration declares correct content type

### LINKED ISSUE #125: Wrong content-Type for tinymce json views
The content type for json views should be application/json.
Now it is text/html:
```
[ale@kenobi plone]$ curl -I plone.org/tinymce-jsonconfiguration |grep Type
Content-Type: text/html
```
This triggers the csrf transform in a way that the json becomes:
```
<html><body><p>{"theme_adv...
ath": false}</p><script src="​.../++resource++protect.js" ...></script></body></html>
```

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #125.

This is for Plone 4.3, once it is closed I can cherry pick the changes to master.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
http://jenkins.plone.org/job/pull-request-4.3/167/

**Comment by ale-rt** [comment]
Wait please, this PR has some issues, apparently the configuration is not loaded always as a json call

**Comment by ale-rt** [comment]
As a note I have fixed my issue by using a view called "tinymce-jsonconfiguration-csrf-free", see:
 - https://github.com/collective/plonetrick.csrfworkarounds/blob/master/plonetrick/csrfworkarounds/browser/tinymce.py#L6

The Content-type I am using is ``text/plain``.

I fear that with this patch the request header will be set when the view is used like shown here:
 - https://github.com/plone/Products.TinyMCE/blob/14d4db4af85fcd31016b6c6237279ba07d4f375a/Products/TinyMCE/skins/tinymce/tinymce_wysiwyg_support.pt#L13

Any suggestions?

**Comment by jensens** [comment]
Hence there was no activity for a long time, I propose to close this PR within next two weeks. If you do not feel ok with this, please speak up and provide us a rough schedule.

**Comment by ale-rt** [comment]
That's fine :)

**Pull request closed without merging**
